@echo off
title Servidor Inventario
echo Iniciando servidor...
call venv\Scripts\activate
echo Aplicando migraciones...
python manage.py migrate
echo Iniciando Daphne (WebSockets + HTTP)...
daphne -b 0.0.0.0 -p 8000 core.asgi:application