# Generated by Django 6.0.2 on 2026-03-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_clientecredito_direccion_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientecredito',
            name='precio_especial',
            field=models.BooleanField(default=False, verbose_name='Precio especial (costo sin IVA)'),
        ),
    ]
