# Generated by Django 6.0.2 on 2026-02-28 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagoticket',
            old_name='monto',
            new_name='monto_total',
        ),
        migrations.AddField(
            model_name='pagoticket',
            name='cliente_credito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='clientes.clientecredito'),
        ),
        migrations.AddField(
            model_name='pagoticket',
            name='monto_efectivo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pagoticket',
            name='monto_recibido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pagoticket',
            name='monto_tarjeta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pagoticket',
            name='vuelto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pagoticket',
            name='metodo',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('mixto', 'Mixto'), ('credito', 'Crédito')], max_length=20),
        ),
    ]
