# Generated by Django 6.0.2 on 2026-03-05 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        ('ventas', '0002_rename_monto_pagoticket_monto_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='es_producto_comun',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='producto_comun_nombre',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='precio_tipo',
            field=models.CharField(choices=[('normal', 'Normal'), ('mayoreo', 'Mayoreo'), ('kit', 'Kit'), ('comun', 'Producto Común')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='productos.producto'),
        ),
    ]
