# Generated by Django 6.0.2 on 2026-03-25 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_movimientocaja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorteCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_corte', models.DateTimeField(auto_now_add=True)),
                ('total_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tarjeta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_credito', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_mixto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cantidad_tickets', models.IntegerField(default=0)),
                ('total_entradas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_salidas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_abonos_credito', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_devoluciones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notas', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_corte'],
            },
        ),
    ]
