# Generated by Django 6.0.2 on 2026-03-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_cortecaja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='precio_tipo',
            field=models.CharField(choices=[('normal', 'Normal'), ('mayoreo', 'Mayoreo'), ('kit', 'Kit'), ('comun', 'Producto Común'), ('devolucion', 'Devolución')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('clausurada', 'Clausurada')], default='pendiente', max_length=20),
        ),
    ]
