# Generated by Django 6.0.2 on 2026-03-28 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_cotizacion_cotizacionitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleventa',
            options={'ordering': ['id'], 'verbose_name_plural': 'Detalles de Venta'},
        ),
    ]
