# Generated by Django 6.0.2 on 2026-04-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_alter_detalleventa_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='precio_tipo',
            field=models.CharField(choices=[('normal', 'Normal'), ('mayoreo', 'Mayoreo'), ('kit', 'Kit'), ('comun', 'Producto Común'), ('devolucion', 'Devolución'), ('descuento', 'Descuento')], default='normal', max_length=10),
        ),
    ]
