# Generated by Django 6.0.2 on 2026-04-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_alter_detalleventa_precio_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacionitem',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
