# Generated by Django 6.0.2 on 2026-04-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_alter_cotizacionitem_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacionitem',
            name='cantidad',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
    ]
