# Generated by Django 6.0.2 on 2026-02-28 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('unidad', 'Unidad'), ('granel', 'Granel'), ('kit', 'Kit')], default='unidad', max_length=10)),
                ('precio_costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('porcentaje_ganancia', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_mayoreo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mayoreo_minimo', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('inventario_actual', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('inventario_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('inventario_maximo', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.categoria')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_promo', models.TextField(blank=True)),
                ('producto', models.OneToOneField(limit_choices_to={'tipo': 'kit'}, on_delete=django.db.models.deletion.CASCADE, related_name='kit', to='productos.producto')),
            ],
            options={
                'verbose_name_plural': 'Kits',
            },
        ),
        migrations.CreateModel(
            name='KitComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='productos.kit')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usado_en_kits', to='productos.producto')),
            ],
            options={
                'verbose_name_plural': 'Componentes de Kit',
                'unique_together': {('kit', 'componente')},
            },
        ),
    ]
