# Generated by Django 6.0.2 on 2026-03-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_movimientoinventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='usa_inventario',
            field=models.BooleanField(default=True),
        ),
    ]
