# Generated by Django 6.0.2 on 2026-02-28 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('stock_bajo', 'Stock Bajo'), ('stock_agotado', 'Stock Agotado'), ('stock_sobre', 'Sobrestock'), ('producto_estancado', 'Producto Estancado'), ('credito_por_vencer', 'Crédito por Vencer'), ('credito_vencido', 'Crédito Vencido'), ('credito_limite', 'Cliente cerca del Límite'), ('abono_registrado', 'Abono Registrado'), ('cierre_caja', 'Cierre de Caja'), ('usuario_nuevo', 'Usuario Nuevo'), ('acceso_denegado', 'Acceso Denegado'), ('venta_credito', 'Venta a Crédito'), ('venta_completada', 'Venta Completada'), ('venta_cancelada', 'Venta Cancelada')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('referencia_id', models.IntegerField(blank=True, null=True)),
                ('referencia_tipo', models.CharField(blank=True, max_length=50)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('destinatario_rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='usuarios.rol')),
                ('destinatario_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-creada'],
            },
        ),
    ]
