# Generated by Django 6.0.2 on 2026-03-03 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('stock_bajo', 'Stock Bajo'), ('stock_agotado', 'Stock Agotado'), ('stock_sobre', 'Sobrestock'), ('producto_estancado', 'Producto Estancado'), ('credito_por_vencer', 'Crédito por Vencer'), ('credito_vencido', 'Crédito Vencido'), ('credito_limite', 'Cliente cerca del Límite'), ('abono_registrado', 'Abono Registrado'), ('cierre_caja', 'Cierre de Caja'), ('usuario_nuevo', 'Usuario Nuevo'), ('acceso_denegado', 'Acceso Denegado'), ('venta_credito', 'Venta a Crédito'), ('venta_completada', 'Venta Completada'), ('venta_cancelada', 'Venta Cancelada')], max_length=30)),
                ('activa', models.BooleanField(default=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_notificacion', to='usuarios.rol')),
            ],
            options={
                'verbose_name': 'Configuración de Notificación',
                'verbose_name_plural': 'Configuraciones de Notificaciones',
                'unique_together': {('rol', 'tipo')},
            },
        ),
    ]
