# Generated by Django 6.0.2 on 2026-03-03 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_configuracionnotificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('sistema', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tipo de Notificación',
                'verbose_name_plural': 'Tipos de Notificación',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='configuracionnotificacion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones', to='notificaciones.tiponotificacion'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones', to='notificaciones.tiponotificacion'),
        ),
    ]
